name: Deploy to Hostinger updated

on:
  push:
    branches:
      - main  # or 'master' if you use that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo_mysql
          tools: composer, npm

      - name: Install dependencies and build assets
        run: |
          composer install
          npm install
          npm run build

      # ✅ Fixed: correctly upload build output directly into /public/build
      - name: Upload built assets to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          port: ${{ secrets.HOSTINGER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          source: "public/build/."
          target: "${{ secrets.HOSTINGER_PATH }}/public/build"
          overwrite: true
          rm: true

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          port: ${{ secrets.HOSTINGER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.HOSTINGER_PATH }}
            git pull origin main
            composer install
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
